### ISSUE TITLE
error  No module named 'spmf'

### ISSUE THREAD

**Issue by Sandy4321** [cavidqlyv/SequencedbSPMF#1]
I get error
builtins.ModuleNotFoundError: No module named 'spmf'

may you help how to run your code?

**Comment by Sandy4321** [comment]
![image](https://user-images.githubusercontent.com/11426119/185809116-679ecc85-33ba-4edb-aa15-9e32ac448c68.png)

**Comment by Sandy4321** [comment]
I use windows OS

**Comment by Sandy4321** [comment]
when I use 
import os
os.system("java -jar spmf.jar")

it directly opens java code GUI
![image](https://user-images.githubusercontent.com/11426119/185809314-6c6f14eb-71f0-454a-9b77-5b1aefaa1c4f.png)

**Comment by Sandy4321** [comment]
it is not clear at all how to use it with your code
https://stackoverflow.com/questions/7372592/python-how-can-i-execute-a-jar-file-through-a-python-script

**Comment by JavidGlyv** [comment]
Dear @Sandy4321 ,
Sorry for the late reply, 

You can install the [SPMF library ](https://pypi.org/project/spmf/) by writing `pip install spmf` to the cmd(terminal)

You can use `spmf_bin_location_dir` argument to locate the spmf.jar file. In this case, it is in the same folders so you can just write `spmf_bin_location_dir="./"`


The code will look like this:
```
spmf = Spmf("GSP", input_filename="data/SequenceDB.txt",
            output_filename="data/GSPFrequentSequence.txt",  arguments=[0.4], spmf_bin_location_dir="./")
```
